cargo-features = ["per-package-target"]

[package]
name = "wacca-led"
version = "0.1.0"
edition = "2021"
default-target="x86_64-pc-windows-gnu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]

[dependencies]
